// function sayHello(name) {
//     return "Hello " + name
// }
// console.log(sayHello("kirtee"))

// Write a function sayBye() which takes 1 argument like user’s name and returns
// “Bye user’s name” ?
// function sayBye(users_name){
//     return "Bye"+" "+users_name
// }
// console.log(sayBye("kirtee"))

// function getFullName(firstName,lastName){
//     console.log(firstName+" "+lastName)
//     }
    
//     getFullName("kumar","nayak");

// function displaySum(num1, num2) {
//     var total = num1 + num2;
//     console.log(total);
//     }
    
    // Calling function
    
    // displaySum(6, 20); // 0utputs: 26
    // displaySum(-5, 17); // 0utputs: 12

    // function displayMultiply(num1, num2, num3) {
    //     return num1*num2*num3
    //     }
        
    //     console.log(displayMultiply(2, 3, 4));
    // function getResult(num1,num2,num3){
    //     console.log(num1-num2+num3)
    //     }
        
    //     getResult(2,3,4,5);

    // function getSum(num1, num2) {
    //     var total = num1 + num2;
    //     return total;
    //     }
    // console.log(getSum(2,4))

    // function getSum(num1, num2) {
    //     var total = num1 + num2;
    //     return total;
    //     }
        
    //     // Displaying returned value
    //     var result1 = getSum(6, 20);
    //     console.log(result1) // 0utputs: 26
    //     var result2 = getSum(-5, 17);
    //     console.log(result2) // 0utputs: 12

    // function averageOfSubjects(maths,science){
    //     return ((maths+science)/2);
    //     }
    //     console.log(averageOfSubjects(25,30));

// function insertingElement(arr){
//     var a=5;
//     arr.push(a);
//     return arr;
// }
// console.log(insertingElement([1,2,3,4]));

// var greet = "Hello World!";
// // Defining function
// function greetWorld() {
// console.log(greet);
// }
// greetWorld(); // Outputs: Hello World!
// console.log(greet); // Outputs: Hello World!
// Visualize
// Edit
// Explanation:


// function getSum(num1, num2) {
//     var total = num1 + num2;
//     return total;
//     }
// console.log(getSum(3,8))


(function myName () {
    var x = "Hello!! Nayak"; // I will invoke myself
    console.log(x);
    })();
